# Generated by Django 4.2.5 on 2023-09-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_pedido', models.CharField(max_length=12)),
                ('codigo_rastreio', models.CharField(max_length=14)),
                ('cpf_cliente', models.CharField(max_length=14)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(max_length=100)),
                ('data_registro', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
