# Generated by Django 4.2.5 on 2023-09-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='data_registro',
            field=models.DateField(),
        ),
    ]
