# Generated by Django 4.2.5 on 2023-09-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_system', '0002_alter_pedidos_data_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='codigo_rastreio',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='id_pedido',
            field=models.CharField(max_length=13),
        ),
    ]
